spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inclined_db
    username: inclined
    password: XXX
  jpa:
    hibernate:
      ddl-auto: none
incident:
  loki:
    base-url: http://116.233.96.74:33100
    label-mapping:
      service: service_name
      env: service
    # k8s环境
#      service: app
#      env: namespace
  notify:
    wecom:
      webhook: ${WECOM_WEBHOOK:}
      enabled: true
    slack:
      webhook: ${SLACK_WEBHOOK:}
      enabled: false
    dingtalk:
      webhook: ${DINGTALK_WEBHOOK:}
      enabled: false
    feishu:
      webhook: ${FEISHU_WEBHOOK:}
      enabled: false



  rule:
    scan-interval-seconds: ${INCIDENT_SCAN_INTERVAL:30}
    mode: ${INCIDENT_MODE:auto}  # external 只接收 Alertmanager/ builtin 只接收 Alertmanager / auto 如果收到 webhook 用 external，否则启用 builtin
  # 没有alertmanager、rule的情况下，平台支持rule
  services: order-server,admin-server
  rules:
    # 默认规则（适用于所有服务）
    - name: default-high-error
      priority: 100
      enabled: true
      match:
        services: ["*"]
      when:
        all:
          - field: errorRate
            op: gt
            value: 5
      severity: P2

    # 指定服务组
    - name: core-service-critical
      priority: 200
      enabled: true
      match:
        services: ["xfxk-*"]
      when:
        all:
          - field: env
            op: eq
            value: dev
          - field: errorRate
            op: gt
            value: 3
      severity: P1

    # 正则匹配
    - name: memory-oom
      priority: 300
      enabled: true
      match:
        servicesRegex: ".*-service"
      when:
        any:
          - field: log
            op: contains
            value: OutOfMemoryError
      severity: P0
