
server:
  port: 8024
  servlet:
    context-path: /api

# 日志配置
logging:
  level:
    root: INFO
    cn.jc.incident: DEBUG
spring:
  application:
    name: incident-community
  profiles:
    active: nodb